export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const SINGIN_USER = "SINGIN_USER"
export const SINGIN_USER_SUCCESS = "SINGIN_USER_SUCCESS"
export const SINGIN_USER_FAIL = "SINGIN_USER_FAIL"

export const FETCH_USERS_LIST = "FETCH_USERS_LIST"
export const USERS_LIST = "USERS_LIST"
export const FETCH_USERS_LIST_FAIL = "FETCH_USERS_LIST_FAIL"